# Generated by Django 2.1 on 2018-09-01 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_auto_20180821_2012'), ('accounts', '0003_auto_20180821_2015'), ('accounts', '0004_auto_20180821_2018'), ('accounts', '0005_profile'), ('accounts', '0006_questions'), ('accounts', '0007_auto_20180829_1814'), ('accounts', '0008_delete_accounts'), ('accounts', '0009_coupling'), ('accounts', '0010_auto_20180831_1543')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('language', models.CharField(choices=[('Türkçe', 'Türkçe'), ('English', 'English')], max_length=20, verbose_name='language')),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PROFILE',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('answer_one', models.CharField(max_length=20)),
                ('answer_two', models.CharField(max_length=20)),
                ('answer_three', models.CharField(max_length=20)),
                ('answer_true', models.CharField(max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('coupling_number', models.IntegerField(default=1)),
                ('coupling_count', models.IntegerField(default=1)),
                ('act_deact', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QUESTIONS',
                'ordering': ['author'],
            },
        ),
        migrations.CreateModel(
            name='COUPLING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.CharField(max_length=25, verbose_name='matche')),
                ('username', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'COUPLING',
                'ordering': ['username'],
            },
        ),
    ]
