# Generated by Django 2.1 on 2018-08-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
