# Generated by Django 2.1 on 2018-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180821_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='language',
            field=models.CharField(choices=[('Türkçe', 'Türkçe'), ('English', 'English')], max_length=20, verbose_name='language'),
        ),
    ]
