# Generated by Django 2.1 on 2018-08-23 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20180821_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('language', models.CharField(choices=[('Türkçe', 'Türkçe'), ('English', 'English')], max_length=20, verbose_name='language')),
                ('user', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PROFILE',
                'ordering': ['id'],
            },
        ),
    ]
