# Generated by Django 2.1 on 2018-08-29 18:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUESTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_one', models.CharField(max_length=20)),
                ('answer_two', models.CharField(max_length=20)),
                ('answer_three', models.CharField(max_length=20)),
                ('answer_true', models.CharField(max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('coupling_number', models.IntegerField(default=1)),
                ('coupling_count', models.IntegerField(default=1)),
                ('active_deactive', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QUESTIONS',
                'ordering': ['author'],
            },
        ),
    ]
