# Generated by Django 2.1 on 2018-08-29 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180829_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ACCOUNTS',
        ),
    ]
