# Generated by Django 2.1 on 2018-08-31 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_delete_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUPLING',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched', models.CharField(max_length=25, verbose_name='eslesilen_hesap')),
                ('username', models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'COUPLING',
                'ordering': ['username'],
            },
        ),
    ]
