# Generated by Django 2.1 on 2018-08-31 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180831_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupling',
            name='username',
            field=models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
