# Generated by Django 2.1 on 2018-08-31 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180831_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user1',
            new_name='user',
        ),
    ]
