# Generated by Django 2.1 on 2018-08-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180831_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='act_deact',
        ),
    ]
