# Generated by Django 2.1 on 2018-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_questions_act_deact'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='act_deact',
            field=models.BooleanField(default=True),
        ),
    ]
