# Generated by Django 2.1 on 2018-08-31 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_questions_act_deact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kullanıcı',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
