# Generated by Django 2.1 on 2018-08-31 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180831_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kullanıcı',
            field=models.OneToOneField(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
