# Generated by Django 2.1 on 2018-08-31 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180831_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kullanıcı',
            field=models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
