# Generated by Django 2.1 on 2018-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180831_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupling',
            name='username',
        ),
        migrations.DeleteModel(
            name='COUPLING',
        ),
    ]
