# Generated by Django 2.1 on 2018-08-31 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20180831_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='kullanıcı',
        ),
    ]
