# Generated by Django 2.1 on 2018-08-31 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180831_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='kullanıcı',
            new_name='user',
        ),
    ]
