# Generated by Django 2.1 on 2018-09-01 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20180901_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupling',
            name='matched_user',
        ),
        migrations.AlterField(
            model_name='coupling',
            name='match_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
