# Generated by Django 2.1 on 2018-09-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20180903_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like_dislike',
            options={'ordering': ['question'], 'verbose_name_plural': 'LIKE_DISLIKE'},
        ),
        migrations.RenameField(
            model_name='like_dislike',
            old_name='like',
            new_name='like_dislike',
        ),
        migrations.RemoveField(
            model_name='like_dislike',
            name='dislike',
        ),
    ]
