# Generated by Django 2.1 on 2018-09-05 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_questions_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
