# Generated by Django 2.1 on 2018-09-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'QUESTIONS'},
        ),
    ]
