# Generated by Django 2.1 on 2018-09-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180910_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'QUESTIONS'},
        ),
    ]
