# Generated by Django 2.1 on 2018-09-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_profile_p_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='ProfilePhoto'),
        ),
    ]
