# Generated by Django 2.1 on 2018-09-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20180916_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_photo',
            field=models.ImageField(blank=True, upload_to='profile_photo', verbose_name='ProfilePhoto'),
        ),
    ]
